### ISSUE TITLE
Upgrade to latest Android and Kotlin flavours of compose

### ISSUE THREAD

**Issue by tamzi** [anselmoalexandre/Compose-Playground-MVI-architecture#37]
Kotlin 1.9.0
and JC 1.5.0

**Comment by anselmoalexandre** [comment]
Quick question on this @tamzi, just do kick start the conversation:
Why updating to Kotlin 1.9.0 🤔? Any specific reason?

I can explain why do I ask this

**Comment by tamzi** [comment]
I mean why not?
- Improved performance
- Latest language features also
